name: rl-virtual-screening
channels:
  - conda-forge
  - plotly
  - anaconda
dependencies:
  - python=3.8
  - numpy=1.19.1
  - matplotlib=3.3.1
  - ipython=7.16.1
  - h5py=2.10.0
  - notebook=6.1.1
  - openbabel=3.1.1
  - scipy=1.5.2
  - rdkit=2020.03.6
  - nodejs=10.13.0
  - psutil=5.6.7
  - pytorch=1.7.1
  - pip=21.1.2
  - pip:
      - tensorflow==2.2.0
      - deepchem==2.5.0
      - pybuilder==0.12.10
      - torch-scatter==2.0.7
      - torch-sparse==0.6.10
      - torch-geometric==1.7.1
